---
include:
  - board: eyelash_sofle_left
    shield: nice_epaper
    snippet: studio-rpc-usb-uart
    #cmake-args:-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n

  - board: eyelash_sofle_right
    shield: nice_epaper

  - board: eyelash_sofle_left
    shield: settings_reset

  - board: eyelash_sofle_left
    shield: eyelash_sofle_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n