---
include:
  - board: eyelash_sofle_left
    shield: nice_epaper
    snippet: studio-rpc-usb-uart
    artifact-name: Sofle_Left

    #cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_sofle_right
    shield: nice_epaper
    artifact-name: Sofle_Right

  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: Sofle_Reset