---
include:
  - board: eyelash_sofle_left
    shield: nice_epaper
    artifact-name: Sofle_Left

    #cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_sofle_right
    shield: nice_epaper
    artifact-name: Sofle_Right

  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: Sofle_Reset

 # Add these cmake-args to the peripherals you wish to use with the dongle
  - board: seeeduino_xiao_ble
    shield: eyelash_sofle_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: Sofle_Dongle