---
include:
  - board: eyelash_sofle_right
    shield: nice_epaper

  # reset_settings
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: nano_reset_settings

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_reset_settings

  # Add custom dongle and a peripheral left
  - board: seeeduino_xiao_ble
    shield: eyelash_sofle_dongle
    snippet: studio-rpc-usb-uart

  - board: eyelash_sofle_left
    shield: nice_epaper
    #snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
