---
#include:
#  - board: eyelash_sofle_left
#    shield: nice_epaper
#    snippet: studio-rpc-usb-uart
#    #cmake-args:-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n

#  - board: eyelash_sofle_right
#    shield: nice_epaper

#  - board: eyelash_sofle_left
#    shield: settings_reset

#  - board: eyelash_sofle_left
#    shield: eyelash_sofle_dongle
#    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

include:
  # Add custom dongle and a peripheral left corne
  - board: seeeduino_xiao_ble
    shield: eyelash_sofle_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: xiao_dongle

  - board: nice_nano_v2
    shield: nice_epaper
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: nano_corne_left

  - board: nice_nano_v2
    shield: nice_epaper
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: nano_corne_right

  # reset_settings
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nano_reset_settings

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_reset_settings
