manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
    - name: drMikeMiles                        #Gem
      url-base: https://github.com/drMikeMiles #Gem
#    - name: mctechnology17                        #LunaModify
#      url-base: https://github.com/mctechnology17 #LunaModify
##############################################################
  projects:
##############################################################
    - name: eyelash_sofle
      url: https://github.com/a741725193/zmk-sofle
      revision: refactor
##############################################################
    - name: Shield                         #Gem
      remote: drMikeMiles                  #Gem
      revision: main                       #Gem
##############################################################
 #   - name: zmk-nice-oled                  #LunaModify
 #     remote: mctechnology17               #LunaModify
 #     revision: main                       #LunaModify
##############################################################
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
##############################################################
  self:
    path: config
